<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 4.6.5.2 setup script
 * Date: Tue, 27 Dec 2016 14:52:50 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: localhost [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = '';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['connect_type'] = 'tcp';
$cfg['Servers'][$i]['nopassword'] = true;
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = '';
$cfg['Servers'][$i]['password'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = true;

/* End of servers configuration */

$cfg['blowfish_secret'] = 'E:X94|w[N%4z;?a_{z2P#E_oXP,|2{9\\';
$cfg['UploadDir'] = '_upload';
$cfg['SaveDir'] = '_upload';
$cfg['LoginCookieValidity'] = 5000;
$cfg['LoginCookieStore'] = 5000;
$cfg['DefaultLang'] = 'zh_TW';
$cfg['ServerDefault'] = 1;
?>